
admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
  tls:
    enabled: false

  ingress:
    enabled: true
    annotations:
      konghq.com/strip-path: "true"
    path: /admin
    ingressClassName: kong

proxy:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-0836ac19a2cd831fe
nodeSelector:
  node-selector-label: kong

tolerations:
  - key: app
    operator: Equal
    value: kong
    effect: NoSchedule


env:
  database: "off"
  trusted_ips: "0.0.0.0/0,::/0"
  #database: "postgres"

plugins:
  goPlugins:
    - pluginName: session-validator

postgresql:
  enabled: false

konga-dashboard:
  enabled: true

image:
  repository: 602037364990.dkr.ecr.us-east-1.amazonaws.com/kong-api-gateway
  tag: "latest"
  pullPolicy: Always
  pullSecrets:
    - regcred
