
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: jwt-secret-creds
#   namespace: {{ .Values.namespaceOverride}}
# type: Opaque
# stringData:
#   kongCredType: jwt
#   key: KzmY6I1AclAZm0AY-uGD_ydt52sXhbcvXR6IVEFeyCw
#   algorithm: ES256
#   rsa_public_key: |-
#     -----BEGIN PUBLIC KEY-----
#     MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEWM2XNhsByrffGyZ+Z71P0MsE9VqT
#     G9AY1GqYq+QeUNxOSSyqmT+avYEk6p3Ts30RZJmTVD4qDUnft8/KgSjreQ==
#     -----END PUBLIC KEY-----
# ---
# apiVersion: configuration.konghq.com/v1
# kind: KongPlugin
# metadata:
#   name: app-jwt
#   namespace: {{ .Values.namespaceOverride}}
#   annotations:
#     kubernetes.io/ingress.class: kong
# config:
#   secret_is_base64: false
#   run_on_preflight: true
#   key_claim_name: iss
#   claims_to_verify:
#     - exp
#   maximum_expiration: 31536000
#   # header_names:
#   #   - x-api-token
#   cookie_names:
#     - x-api-token
#   uri_param_names:
#     - x-api-token
# plugin: jwt
# ---
# apiVersion: configuration.konghq.com/v1
# kind: KongConsumer
# metadata:
#   name: jwt-consumer
#   namespace: {{ .Values.namespaceOverride}}
#   annotations:
#     kubernetes.io/ingress.class: kong
# username: apiUser
# credentials:
#   - jwt-secret-creds
# ---