apiVersion: v1
kind: Secret
metadata:
  name: sentieo.com.tls
  namespace: kong
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "ssl-certs/sentieo.com.crt"}}
  tls.key: {{ .Files.Get "ssl-certs/sentieo.com.key"}}