apiVersion: v2
description: The Cloud-Native Ingress and API-management
engine: gotpl
home: https://konghq.com/
icon: https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-large.png
maintainers:
- name: chalukya
  email: chalukya@sentieo.com
name: kong
sources:
- https://github.com/Kong/charts/tree/main/charts/kong
version: 2.11.1

appVersion: "2.8"
dependencies:
- name: postgresql
  version: 11.1.15
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: konga
  version: 0.2.0
  repository: https://usernames.github.io/konga-helm
  condition: konga-dashboard.enabled
